# -*- coding: utf-8 -*-
"""ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KIIpAJYAvRLXyPUNbIUDFdmhBOW2HFC1
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.linear_model import LinearRegression

df = pd.read_csv("/content/NCRB_Table_1A.1.csv")
print(df.head(5))

print("shape of dataset",(df.shape))

print("columns:",df.columns)

print("dataset description",df.describe())

print("dataset info:",df.info())

df.drop(columns=['Sl. No.'])

df.isnull().sum()

df = df.drop(columns=['Sl. No.'])
df

df = df.rename(columns={'State/UT':'State'})
df

crime_state = df['State']
year_2020 = df['2020']

plt.figure(figsize=(10,8))
plt.barh(crime_state,year_2020,color='orange')
plt.xlabel("Crimes")
plt.ylabel("States")
plt.title(" Crimes in INDIA 2020")
plt.tight_layout()
plt.show()

india_total = df[df['State']=="Total All India"]
india_total

years = india_total.columns[1:]
years

crimes = india_total.iloc[0,1:]
crimes

years = ['2020','2021','2022']
crimes = crimes.astype(int)

years
crimes

plt.plot(years,crimes,marker='o')
plt.xlabel("Year")
plt.ylabel("Crimes")
plt.title("Crimes in India Trend")
plt.ticklabel_format(style='plain',axis='y')
plt.show()

years = np.array([2020,2021,2022])
crimes = np.array(crimes)

x = years.reshape(-1,1)
y = crimes

model = LinearRegression()
model.fit(x,y)

future_year = np.array([2023,2024,2025,2026])
future_year = future_year.reshape(-1,1)

prediction = model.predict(future_year)
prediction

Year = ['2023','2024','2025','2026']
plt.plot(Year,prediction,marker='o',color='red')
plt.xlabel("Year")
plt.ylabel("Crimes")
plt.title("Crimes in India Trend")
plt.ticklabel_format(style='plain',axis='y')
plt.show()

all_years = np.concatenate((years,future_year.flatten()))
all_years

combined_crimes = np.concatenate((crimes, prediction))

plt.bar(all_years, combined_crimes)
plt.xlabel("Year")
plt.ylabel("Crimes")
plt.title("Crimes in India Trend (with Predictions)")
plt.ticklabel_format(style='plain',axis='y')
plt.show()